### ISSUE TITLE
change title color 

### ISSUE THREAD

**Issue by nikhilpsathyanathan** [salyangoz/updateme-android#7]
is there anyway to set title color and button color

**Comment by nikhilpsathyanathan** [comment]
.setTopColorRes(R.color.darkBlueGrey) from LovelyInfoDialog is not detecting

**Comment by salyangoz** [comment]
Hello @nikhilpsathyanathan ,

You can find this in our new version. Import it using;

    implementation 'io.salyangoz.updateme:updateme:0.1.2'
